version: '2'
services:
  node_java:
    extends:
      file: code/node_java/docker-compose.node-java.yml
      service: node
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      NODE_DEBUG: "False"

  node:
    extends:
      file: node.docker-compose.yml
      service: node
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      NODE_DEBUGGER: "False"

    # entrypoint: ["/bin/bash"]

    #  docker run -ti --entrypoint /bin/bash 9b6a81855c06
    #  d-c run --entrypoint /bin/bash node-3
    #  NODE_ID=3 NODE_TOTAL=4 POSSIBLE_FAILURES=1 NODE_HOST=teamproject16_node-{i}_1 NODE_PORT=4458 python main_node.py

  api:
    extends:
      file: api.docker-compose.yml
      service: api
    ports:
      - "80:80"
    restart: "no"
    command: ["python", "main_api.py"]

    #entrypoint: []
    #command: ["ls", "-la"]

  postgres:
    extends:
      file: api.docker-compose.yml
      service: postgres

  postgres_browser:
    extends:
      file: api.docker-compose.yml
      service: postgres_browser
