version: '2'
services:
  node:
    build: .
    environment:
      NODE_ID:
      NODE_TOTAL: 4
      POSSIBLE_FAILURES: 1
      NODE_PORT: 4458
    # restart: "unless-stopped"
    # stdin_open: true

