version: '2'
services:
  node:
    extends:
      file: docker-compose.node.yml
      service: node
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      NODE_DEBUGGER: "False"

    # entrypoint: ["/bin/bash"]

    #  docker run -ti --entrypoint /bin/bash 9b6a81855c06
    #  d-c run --entrypoint /bin/bash node-3
    #  NODE_ID=3 NODE_TOTAL=4 POSSIBLE_FAILURES=1 NODE_HOST=teamproject16_node-{i}_1 NODE_PORT=4458 python main.py
