version: '2'
services:
  node:
    build:
      context: .
      dockerfile: ./code/node/Dockerfile
    command: ["main_node.py"]
    environment:
      DOCKER_CACHING_TIME: 5
      NODE_PORT: 4458
      NODE_DEBUGGER: 0
