version: '2'
services:
  node:
    extends:
      file: docker-compose.node.yml
      service: node
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      NODE_DEBUGGER: "False"

    # entrypoint: ["/bin/bash"]

    #  docker run -ti --entrypoint /bin/bash 9b6a81855c06
    #  d-c run --entrypoint /bin/bash node-3
    #  NODE_ID=3 NODE_TOTAL=4 POSSIBLE_FAILURES=1 NODE_HOST=teamproject16_node-{i}_1 NODE_PORT=4458 python main_node.py

  db_proxy:
    extends:
      file: docker-compose.db_proxy.yml
      service: db_proxy
    ports:
      - "80:80"
    restart: "no"
    command: ["python", "main_db_proxy.py"]

    #entrypoint: []
    #command: ["ls", "-la"]

  postgres:
    extends:
      file: docker-compose.db_proxy.yml
      service: postgres

  postgres_browser:
    extends:
      file: docker-compose.db_proxy.yml
      service: postgres_browser
