version: '2'
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    # command: ["sleep", "1231312462384628347623847"]
    # interactive: true
    #environment:
    #  DOCKER_CACHING_TIME: 5
    #  NODE_PORT: 4458
    #  NODE_DEBUGGER: 0
